test:
  imports:
    - python_packaging_tools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/wpk-nist-gov/python-packaging-tools
  summary: Demos on better python packaging
  description: |
    Demos on better python packaging
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
